config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

import products

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("products.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import product, cart, checkout


app_name="products"

urlpatterns=[

    path("",product,name="product"),
    path("cart/",cart,name="cart"),
    path("checkout/",checkout,name="checkout"),
]

products/models.py
from django.db import models
from django.contrib.auth.models import User


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True,blank=True)
    email = models.CharField(max_length=200, null=True,blank=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    name=models.CharField(max_length=200, null=True)
    price=models.FloatField(default=0.0)
    digital=models.BooleanField(default=False,null=True,blank=True)
    image=models.ImageField(null=True,blank=True)
    def __str__(self):
        return self.name

    @property
    def imageUrl(self):
        try:
            url=self.image.url
        except:
            url=''
        return url
class Order(models.Model):
    customer=models.ForeignKey(Customer,on_delete=models.SET_NULL,blank=True,null=True)
    date_ordered=models.DateTimeField(auto_now_add=True)
    complete=models.BooleanField(default=False)
    transaction_id=models.CharField(max_length=200,null=True)

    def __str__(self):
        return str(self.id)

    @property
    def get_cart_total(self):
        orderitems=self.orderitem_set.all()
        total=sum([item.get_total for item in orderitems])
        return total
    @property
    def get_cart_items(self):
        orderitems=self.orderitem_set.all()
        total=sum([item.quantity for item in orderitems])
        return total

class OrderItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.SET_NULL,blank=True,null=True)
    order=models.ForeignKey(Order,on_delete=models.SET_NULL,blank=True,null=True)
    quantity=models.IntegerField(default=0,null=True,blank=True)
    date_added=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.name
    @property
    def get_total(self):
        total=self.product.price*self.quantity
        return total


class Shipping(models.Model):
    customer=models.ForeignKey(Customer,on_delete=models.SET_NULL,blank=True,null=True)
    order=models.ForeignKey(Order,on_delete=models.SET_NULL,blank=True,null=True)
    address=models.CharField(max_length=200,null=True)
    city=models.CharField(max_length=200,null=True)
    state=models.CharField(max_length=200,null=True)
    zipcode=models.CharField(max_length=200,null=True)
    date_added=models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.address
        
    

products/views.py
from .models import *
from django.http import request
from django.shortcuts import render


def product(request):
    products=Product.objects.all()
    context={
        "products":products
    }
    return render(request, 'product.html', context)

def cart(request):
    if request.user.is_authenticated:
        customer=request.user.customer
        order,created=Order.objects.get_or_create(customer=customer,complete=False)
        items=order.orderitem_set.all()
    else:
        customer, order = guestOrder(request, data)
        items=[]
        order={
            'get_cart_total':0,'get_cart_items':0,'shipping':False
        }
    
        context={
            "items":items,
            "order":order,

        }
        return render(request, 'cart.html', context)
      

def checkout(request):

    if request.user.is_authenticated:
        customer=request.user.customer
        order,created=Order.objects.get_or_create(customer=customer,complete=False)
        items=order.orderitem_set.all()
        context={
            "items":items,
            "order":order,

        }
        return render(request, 'checkout.html', context)

    # else:
    #     items=[]
    #     order={
    #         'get_cart_total':0,'get_cart_items':0,'shipping':False
    #     }
    
    #     context={
    #         "items":items,
    #         "order":order,

    #     }
    #     return redirect('products:product')
    # return render(request, 'checkout.html',context)

frontend/templates/cart.html
{% extends 'main.html' %} 
{%  load static   %}
{% block body %}
<div class="row">
    <div class="col-lg-12">
        <div class="box-element">
            <a class="btn btn-outline-dark" href="{% url 'products:product' %}">&#x2190 Continue Shopping</a>
            <br>
            <br>
            <table class="table">
                <tr>
                    <th> <h5> ITEMS:<strong>${{order.get_cart_items}}</strong></h5></th>
                    <th> <h5> TOTAL:<strong>${{order.get_cart_total}}</strong></h5></th>
                    <th> <a style="float:right;margin:5px;" class="btn btn-success" href="{% url 'products:checkout' %}">
                        Checkout</a></th>
                </tr>
            </table>

        </div>

        <br>
        <div class="box-element">
            <div class="cart-row">
                <div stlye="flex:2"></div>
                <div style="flex:2"> <strong> Item: </strong></div>
                <div style="flex:1">  <strong> Price:  </strong></div>
                <div style="flex:1"> <strong> Quantity: </strong> </div>
                <div style="flex:1"> <strong> Total:  </strong></div>
            </div>
            {% for item in items %}
            <div class="cart-row">
                <div stlye="flex:2"> <img class="row-image" src="{{item.imageURL}}"> </div>
                <div style="flex:2">{{item.name}}</div>
                <div style="flex:1">${{item.price|floatformat:2}}</div>
                <div style="flex:1">
                    <p class="quantity">{{item.quantity}}</p>
                    <div class="quantity">
                        <img class="chg-quantity" src="{% static 'images/up.png' %}">
                        <img class="chg-quantity" src="{% static 'images/down.png' %}">
                    </div>
                </div>
                <div style="flex:1">@{{item.get_total}}</div>
            </div>
            {% endfor %}
        </div>

    </div>
</div>
{% endblock %}

frontend/templates/checkout.html
{% extends 'main.html' %} 

{%  load static %}
{% block body %}
<div class="row">
    <div class="col-lg-6">
        <div class="box-element" id="form-wrapper">
            <form id="form">
                <div id="user-info">
                   <div class="form-field">
                    <labke>Name:</lable><br>
                    <input required class="form-control",type="text"name="name", placeholder="name.....">
                   </div>
                   <div class="form-field">
                    <labke>Email:</lable><br>
                    <input required class="form-control",type="text"name="email", placeholder="email.....">
                   </div>
                 <div>
                <div id="shipping-info">
                    <hr>
                    <p>Shipping Information</p>
                    <hr>
                    <div class="form-field">
                        <input required class="form-control",type="text"name="address", placeholder="address.....">
                       </div>
                       <div class="form-field">
                        <input required class="form-control",type="text"name="city", placeholder="city.....">
                       </div>
                       <div class="form-field">
                        <input required class="form-control",type="text"name="state", placeholder="state.....">
                       </div>
                       <div class="form-field">
                        <input required class="form-control",type="text"name="zip Code", placeholder="zip Code.....">
                       </div>

                <div>
                    <hr>
                    <input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
            </form>

        </div>
        <br>
         <div class="box-element hidden" id="payment-info">
            <small>Payment Options</small>
         </div>
    </div>
    <div class="col-lg-6">
        <div class="box-element">
        <a class="btn btn-outline-dark" href="{% url 'products:cart' %}">&#x2190 Back to Cart</a>
        <hr>
        <h3>Order Summary</h3>
        <hr>
        {% for item in items %}
        <div class="cart-row">
            <div style="flex:2"> <img class="row-image" src="{{item.product.imageURL}}"> </div>
            <div style="flex:2">{{item.product.name}}</div>
            <div style="flex:1">${{item.product.price}}</div>
            <div style="flex:1">x2{{item.quantity}}</div>
        </div>
        {% endfor %}
        <h4>Items:{{order.get_cart_items}}</h4>
        <h4>Items:{{order.get_cart_total| floatformat }}</h4>
        </div>
    </div>
</div>
{% endblock %}

frontend/templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
  
        <title>Ecom</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link href="{% static '/css/main.css' %}" rel="stylesheet">   
          
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <a class="navbar-brand" href="{% url 'products:product' %}">Ecom</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url  'products:product' %}">Products</a>
              </li>
              <div class="form-inline  my-2 my-lg-0" >
                <a href="#" class="btn btn-warning">Login</a>
                <a href="{% url 'products:cart' %}"><img id="cart-icon" src="{% static "images/cart.jpg" %}"></a>
                <p id="cart-total">0</p>
              </div>
            </ul>

          </div>
        </nav>
    
      <div class="container">
        {% block body %}

        {% endblock %}
      </div>
      
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<script src="{%  static '/js/cart.js' %}"></script>
</body> 
</html>

frontend/templates/product.html
{% extends 'main.html' %} 

{% load static  %}
{% block body %}

<div class="row">
   {% for pro in products %}
    <div class="col-lg-4">
        <img class="thumbnail" src="{{pro.imageUrl}}">
        <div class="box-element product">
            <strong> <h4>{{pro.name}}</h4></strong>
            <hr>
            <button data-product={{product.id}} data-action="add" class="btn btn-outline-secondary add-btn update-cart"> Add To Cart</button>
            <a href="#" class="btn btn-outline-success">View</a>
            <h4 style="display:inline-block;float:right;">${{pro.price|floatformat:2}}</h4>
        </div>  
    </div>
    {% endfor %}
</div>
{% endblock %}